# Generated by Django 4.2.2 on 2025-07-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('draft', 'Черновик'), ('consid', 'На рассмотрении')], default='consid', max_length=30, verbose_name='Статус поста'),
        ),
    ]
